package drools
 
import java.util.Map;
import java.lang.String;
import com.neustar.iot.spark.rules.RulesForwardWorker;

global RulesForwardWorker worker 
global String rest_Uri
global String jdbc_url
global String hdfs_url 
global String result 
dialect "java"


rule "Registry Put"
    when
        $messageMap : Map( this["messagetype"] == "REGISTRY" )             
    then
        RulesForwardWorker worker = new RulesForwardWorker();
        rest_Uri =  new String("http://ec2-52-41-124-186.us-west-2.compute.amazonaws.com:8080");
        result = worker.remoteRestGet(rest_Uri, $messageMap,  null);
        
        $messageMap.put("endpoint_uri", rest_Uri);
        $messageMap.put("result", result);
        System.out.println("Message sent to registry put returned : " + result );
        rest_Uri  =  new String("https://search-iotaselasticsearch-qtpuykpxgabuzfidzncsfyp7k4.us-west-2.es.amazonaws.com/ioteventindex/registry");
        String ret = worker.remoteElasticSearchPost(rest_Uri, $messageMap,  null);
        System.out.println("Message sent to ElasticSearch returned : " + ret );
end

