package drools

import java.util.Map;
import java.util.HashMap;
import java.lang.String;
import com.neustar.iot.spark.rules.RulesForwardWorker;

global RulesForwardWorker worker
global Map<String,Object> attrMap
global String rest_Uri
global String jdbc_url
global String hdfs_url
global String result

dialect "java"


rule "Registry Post"
    when
        $messageMap : Map( this["messagetype"] == "REGISTRY_POST" )
    then
        worker = new RulesForwardWorker();
        rest_Uri =  new String("http://54.149.9.196:8080");
        attrMap = new HashMap<String,Object>();
			attrMap.put("path", "/api/v1/devices/54919CA5-4101-4AE4-595B-353C51AA983C/rshadow");
			attrMap.put("header", "{\"API-KEY\": \"2\",\"Content-Type\": \"application/json\"}");
			
        result = worker.remoteRestPost(rest_Uri, $messageMap,  attrMap);

        $messageMap.put("endpoint_uri", rest_Uri);
        $messageMap.put("result", result);
        System.out.println("Message sent to registry put returned : " + result );
        rest_Uri  =  new String("https://search-iotaselasticsearch-qtpuykpxgabuzfidzncsfyp7k4.us-west-2.es.amazonaws.com/ioteventindex/registry");
        String ret = worker.remoteElasticSearchPost(rest_Uri, $messageMap,  null);
        System.out.println("Message sent to ElasticSearch returned : " + ret );
end


rule "Registry Put"
    when
        $messageMap : Map( this["messagetype"] == "REGISTRY_PUT" )
    then
        worker = new RulesForwardWorker();
        rest_Uri =  new String("http://54.149.9.196:8080");
        attrMap = new HashMap<String,Object>();
			attrMap.put("path", "/api/v1/devices/update");
			attrMap.put("header", "{\"API-KEY\": \"0\",\"Content-Type\": \"application/json\"}");
			
        result = worker.remoteRestPut(rest_Uri, $messageMap,  attrMap);

        $messageMap.put("endpoint_uri", rest_Uri);
        $messageMap.put("result", result);
        System.out.println("Message sent to registry put returned : " + result );
        rest_Uri  =  new String("https://search-iotaselasticsearch-qtpuykpxgabuzfidzncsfyp7k4.us-west-2.es.amazonaws.com/ioteventindex/registry");
        String ret = worker.remoteElasticSearchPost(rest_Uri, $messageMap,  null);
        System.out.println("Message sent to ElasticSearch returned : " + ret );
end

rule "ElasticSearch Post"
    when
         $messageMap : Map( this["messagetype"] == "NOTIFICATION" )
    then
                worker = new RulesForwardWorker();
        rest_Uri  =  new String("https://search-iotaselasticsearch-qtpuykpxgabuzfidzncsfyp7k4.us-west-2.es.amazonaws.com/ioteventindex/registry");
        String ret = worker.remoteElasticSearchPost(rest_Uri, $messageMap,  null);

        $messageMap.put("endpoint_uri", rest_Uri);
        $messageMap.put("result_registry", ret);
        System.out.println("Message sent to ElasticSearch returned : " + ret );
end